THRESHOLD = 0.1
X_COLS = [
    "bin_number",
    "mean_hr",
    "diastolicbp_mean",
    "resprate_mean",
    "spo2_mean",
    "systolicbp_mean",
    "temp_mean",
    "meanbp_mean",
    "age",
    "history_of_icu_admission",
    "resp_rate_last",
    "hr_last",
    "mean_bp_last",
    "male_gender",
    "ccu_unit",
    "systolic_bp_last",
    "spo2_last",
    "platelet_count_last",
    "tobacco",
    "hemoglobin_last",
    "tsicu_unit",
    "nicu_unit",
    "wbc_count_last",
    "csru_unit",
    "blood_lactate_last",
    "diastolic_bp_last",
    "potassium_last",
    "bun_last",
    "arterial_ph_last",
    "temp_last",
    "nward_unit",
    "micu_unit",
    "creatinine_last",
    "sicu_unit",
]

X_COLS_TS = {
    "bin_number",
    "diastolicbp_mean",
    "mean_hr",
    "meanbp_mean",
    "resprate_mean",
    "spo2_mean",
    "systolicbp_mean",
    "temp_mean",
}

X_COLS_BASE = set(X_COLS) - X_COLS_TS
